= LPT Capture

Capture text from a parallel port to a file, then convert that to a LibreOffice document. Assumes that the format is plain text.

This consists of hardware/firmware in src and PC, Linux, software in pcsrc.
Micro controller code is C AVR not Arduino.  Do:
[source, bash]
make install

To build and install.  Edit the Makefile for your favourite installer tool.

First build your device using the schematic.
I used perf-board and wires since the wiring is very simple.  Resistor values are 1K but other values around this may work too.
No resistors at all will also work but may expose your parallel port to currents it can's handle.
There should probably be voltage spike protection too with suitable diodes.


Compile with

[source, bash]
gcc eps_convert.c -o eps_convert


== How to Use

- Plug it in to the port you want to capture from and a USB cable.
- Press Print on the device.  It should wait until a printer becomess attached
- Do

[source, bash]
./eps_convert /dev/ttyUSB0 report.fodt

Command line arguments are input port and output file name.

Then.

[source, bash]
libreoffice7.0 printfile.fodt

To open the file in LibreOffice Writer.  Obviously use the version you have installed.
Or you can do all that mouse clicky malarky in your GUI.

Enjoy.  Also post bugs and improvements.

This was really a one off for some specific data I need to liberate, hence all the hard coded file names and paths.

I need to make it more generic.  Maybe.
